name: Solar Theme
url: https://netbuk.github.io
baseurl: /solar-theme-jekyll/
description: A stylish blog using the Solarized color palette

layouts_dir: _layouts

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
